name = "certiflow-backend"
main = "src/index.ts"
compatibility_date = "2026-05-12"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NODE_ENV = "production"

[[rules]]
type = "Data"
globs = ["**/*.docx"]
fallthrough = true
